# Generated by Django 2.1.5 on 2019-06-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_cost',
            field=models.IntegerField(),
        ),
    ]
