# Generated by Django 2.1.5 on 2019-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190621_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_cost',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
