# Generated by Django 2.1.5 on 2019-06-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20190621_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='is_ordered',
            field=models.BooleanField(default=True),
        ),
    ]
